#!/usr/bin/env node
import crypto from "node:crypto";
import fs from "node:fs/promises";
import path from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(scriptDir, "..");
const sourceDir = path.join(root, "data", "pib");
const importDir = path.join(root, "data", "pib-import");
const collectionSlug = "psychedelic-information-bulletin";
const collectionId = uuidFromString(`collection:${collectionSlug}`);
const publishedAt = "2026-05-15T00:00:00.000Z";

async function main() {
  const entries = await fs.readdir(sourceDir, { withFileTypes: true });
  const pdfs = entries
    .filter((entry) => entry.isFile() && entry.name.toLowerCase().endsWith(".pdf"))
    .map((entry) => entry.name)
    .sort((a, b) => issueNumberFromFilename(a) - issueNumberFromFilename(b));

  if (!pdfs.length) {
    throw new Error(`No PDFs found in ${sourceDir}`);
  }

  await fs.mkdir(importDir, { recursive: true });

  const collections = [
    {
      id: collectionId,
      slug: collectionSlug,
      title: "Psychedelic Information Bulletin",
      subtitle: "Trial issue-level import",
      summary:
        "A pilot compound-source import for the Psychedelic Information Bulletin / PIC Bulletin, organized as issue-level PDF records.",
      body:
        "This trial collection keeps the periodical run at collection level while preserving each issue as its own archive source with an original PDF.",
      status: "published"
    }
  ];

  const documents = [];
  const files = [];
  const assets = [];
  const collectionDocuments = [];

  for (const filename of pdfs) {
    const issueNumber = issueNumberFromFilename(filename);
    const year = yearFromFilename(filename);
    const slug = `pic-bulletin-${issueNumber}`;
    const documentId = uuidFromString(`document:${slug}`);
    const fileId = uuidFromString(`file:${slug}:original-pdf`);
    const storagePath = `documents/${slug}/original/source.pdf`;
    const localPath = path.relative(importDir, path.join(sourceDir, filename));
    const stat = await fs.stat(path.join(sourceDir, filename));

    documents.push({
      id: documentId,
      slug,
      title: `PIC Bulletin ${issueNumber}`,
      short_title: `No. ${issueNumber}`,
      source_kind: "collection_item",
      parent_collection_id: collectionId,
      sequence_label: `No. ${issueNumber}`,
      sequence_number: issueNumber,
      issue_date: year ? String(year) : null,
      display_date: year ? String(year) : "Date pending",
      date_start: year,
      document_type: "Source",
      medium: "Text",
      language: "English",
      region: "United States",
      publication_title: "Psychedelic Information Bulletin",
      publisher: "Psychedelic Information Center",
      summary: `Issue ${issueNumber} of the Psychedelic Information Bulletin / PIC Bulletin.`,
      citation: `Psychedelic Information Center. "PIC Bulletin ${issueNumber}." ${year ?? "n.d."}.`,
      rights_statement: "Rights status pending review. Trial PDF import for archive organization testing.",
      source_url: "#",
      access_type: "hosted",
      hosting_status: "pdf",
      reader_mode: "pdf",
      is_featured: false,
      status: "published",
      published_at: publishedAt
    });

    files.push({
      id: fileId,
      document_id: documentId,
      page_id: null,
      kind: "original_pdf",
      storage_path: storagePath,
      mime_type: "application/pdf",
      byte_size: stat.size
    });

    assets.push({
      local_path: localPath,
      storage_path: storagePath,
      mime_type: "application/pdf"
    });

    collectionDocuments.push({
      collection_id: collectionId,
      document_id: documentId,
      position: issueNumber,
      sequence_label: `No. ${issueNumber}`,
      sequence_number: issueNumber,
      issue_date: year ? String(year) : null,
      editorial_caption: `PIC Bulletin ${issueNumber}`
    });
  }

  const emptyTables = {
    pages: [],
    page_lines: [],
    external_sources: [],
    people: [],
    document_people: [],
    document_sections: [],
    document_figures: [],
    tags: [],
    document_tags: []
  };

  await writeJson("collections", collections);
  await writeJson("collection_documents", collectionDocuments);
  await writeJson("documents", documents);
  await writeJson("files", files);
  await writeJson("assets", assets);

  for (const [name, rows] of Object.entries(emptyTables)) {
    await writeJson(name, rows);
  }

  await fs.writeFile(
    path.join(importDir, "README.md"),
    [
      "# PIB Trial Import",
      "",
      "Generated by `node scripts/import_pib_trial.mjs` from `data/pib/*.pdf`.",
      "",
      `Collection slug: \`${collectionSlug}\``,
      "",
      "Import with:",
      "",
      "```bash",
      "SUPABASE_URL=\"https://yqcvybdabpnxyapnrjlp.supabase.co\" \\",
      "SUPABASE_SERVICE_ROLE_KEY=\"your_secret_key\" \\",
      "SUPABASE_STORAGE_BUCKET=\"archive-assets\" \\",
      "node scripts/upload_squarespace_to_supabase.mjs --import-dir data/pib-import",
      "```",
      ""
    ].join("\n"),
    "utf8"
  );

  console.log(`Generated PIB trial import with ${documents.length} issue records in ${path.relative(root, importDir)}`);
}

async function writeJson(name, value) {
  await fs.writeFile(path.join(importDir, `${name}.json`), `${JSON.stringify(value, null, 2)}\n`, "utf8");
}

function issueNumberFromFilename(filename) {
  const match = filename.match(/\bBulletin\s+(\d+)\b/i);
  if (!match) throw new Error(`Could not parse issue number from ${filename}`);
  return Number(match[1]);
}

function yearFromFilename(filename) {
  const match = filename.match(/\b(19\d{2}|20\d{2})\b/);
  return match ? Number(match[1]) : null;
}

function uuidFromString(value) {
  const hash = crypto.createHash("sha1").update(value).digest();
  const bytes = Buffer.from(hash.subarray(0, 16));
  bytes[6] = (bytes[6] & 0x0f) | 0x50;
  bytes[8] = (bytes[8] & 0x3f) | 0x80;
  const hex = bytes.toString("hex");
  return `${hex.slice(0, 8)}-${hex.slice(8, 12)}-${hex.slice(12, 16)}-${hex.slice(16, 20)}-${hex.slice(20)}`;
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
